package payment.util;

public interface ExceptionConstant {

    String ERROR_LEVEL_IS_BLOCKER = "ERROR_LEVEL_IS_BLOCKER";

    String ERROR_LEVEL_IS_CRITICAL = "ERROR_LEVEL_IS_CRITICAL";

    String ERROR_LEVEL_IS_MAJOR = "ERROR_LEVEL_IS_MAJOR";

    String ERROR_LEVEL_IS_NORMAL = "ERROR_LEVEL_IS_NORMAL";
    String ERROR_LEVEL_IS_MINOR = "ERROR_LEVEL_IS_MINOR";
}
